remove wallet param from internal deletion methods, use Config type
TODO replace unwrap() on config with match

I had to use an unwrap here:

```
let _config = Config::from_str(c_conf.to_str().unwrap()).unwrap(); // TODO handle error here
```

Instead of matching like:
```
    let _config = match Config::from_str(c_conf.to_str().unwrap()) {
        Ok(config) => {
            config
        }, Err(err) => {
            let error_msg = format!("Error getting config in rust_delete_wallet{}", &err.to_string());
            let error_msg_ptr = CString::new(error_msg).unwrap();
            let ptr = error_msg_ptr.as_ptr(); // Get a pointer to the underlying memory for s
            std::mem::forget(error_msg_ptr);
            ptr
        }
    };
```
or
```
...
        }, Err(err) => {
            return Err(Error::from(ErrorKind::GenericError(format!(
                "Error getting config in rust_delete_wallet: {}",
               err.to_string()
            ))))
        }
```

because they cause errors like

```
error[E0308]: mismatched types
   --> src/lib.rs:814:20
    |
814 |               return Err(Error::from(ErrorKind::GenericError(format!(
    |  ____________________^
815 | |                 "Error getting config in rust_delete_wallet: {}",
816 | |                 err.to_string()
817 | |             ))))
    | |________________^ expected *-ptr, found enum `Result`
    |
    = note: expected raw pointer `*const i8`
                      found enum `Result<_, stack_epic_wallet_libwallet::Error>`

For more information about this error, try `rustc --explain E0308`.
warning: `epic-cash-wallet` (lib) generated 11 warnings
error: could not compile `epic-cash-wallet` due to previous error; 11 warnings emitted
```
and

```
error[E0308]: `match` arms have incompatible types
   --> src/lib.rs:813:13
    |
805 |       let _config = match Config::from_str(c_conf.to_str().unwrap()) {
    |  ___________________-
806 | |         Ok(config) => {
807 | |             config
    | |             ------ this is found to be of type `Config`
808 | |         }, Err(err) => {
...   |
813 | |             ptr
    | |             ^^^ expected struct `Config`, found *-ptr
...   |
818 | |         }
819 | |     };
    | |_____- `match` arms have incompatible types
    |
    = note:   expected struct `Config`
            found raw pointer `*const i8`
```